source 'https://github.com/CocoaPods/Specs.git'

use_frameworks!

platform :ios, '8.0'

target 'SDKRepo_Example' do
  pod 'SDKRepo', :path => '../'

  target 'SDKRepo_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase'
  end
end
